baseurl = "https://jan-schaller.eu"
title = "Home"
theme = "hugo-coder"
languagecode = "de"
defaultcontentlanguage = "de"

publishDir = "docs"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Jan Schaller"
    info = "Politikwissenschaftler | Migrationsforschung | digitales Arbeiten"
    description = "Persönliche Website von Jan Schaller"
    keywords = "blog,research,personal"
    avatarurl = "images/avatar.jpg"

   # favicon_32 = "/img/favicon-32x32.png"
   # favicon_16 = "/img/favicon-16x16.png"

    footercontent = "Zwerge auf den Schultern von Riesen"
    hidecredits = false
    hidecopyright = true

    rtl = false

    math = true
    custom_css = ["css/coder.min.28d751104f30c16da1aa1bb04015cbe662cacfe0d1b01af4f2240ad58580069c.css"]

# Perma links
[permalinks]
	pages = "/:title/" 

# Social links
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 1
    url = "https://twitter.com/_janschaller"
[[params.social]]
    name = "Research Gate"
    icon = "fab fa-researchgate fa-2x"
    weight = 2
    url = "https://www.researchgate.net/profile/Jan-Schaller"


# Menu links

[[menu.main]]
    name = "Über mich"
    weight = 1
    url = "/Lebenslauf/"
[[menu.main]]
    name = "Wissenschaft"
    weight = 2
    url = "https://trawos.hszg.de/projekte-publikationen/aktuelle-projekte/soziale-integration-ohne-eliten"
[[menu.main]]
    name = "Papierlos Arbeiten"
    weight = 3
    url = "/papierlos-arbeiten/"
[[menu.main]]
    name = "Politische Texte"
    weight = 4
    url = "/undogmatisch/"
[[menu.main]]
    name = "Vorträge & Kontakt"
    weight = 5
    url = "/Kontakt/"
